### ISSUE TITLE
Modal Component

### ISSUE THREAD

**Issue by ergenekonyigit** [Trendyol/baklava-react-native#17]
## Design

[Figma Design Document](https://www.figma.com/file/9r2IU29t66u2rsxX49H8zE/Baklava-Mobile-Design-Guide?type=design&node-id=138-1986&mode=design&t=RY3dzwoOuzYClevA-0)

## Implementation

General usage example:

```jsx
<Modal
   title="Title"
   closeButtonAction = { () => {} }
   actionButtonProps={{ onPress: () => {}, text: "text"}}
   secondActionButtonProps={{ onPress: () => {}, text: "text"}}
>
   <Box/>
</Modal>
```

### Rules

- By default a modal contains a title, a close button and a primary action button.
- Modals are closeable. By default it closes by close button, and by clicking outside of the dialog.
- A modal should contain at least one content (text, image etc.).
- Only large buttons can be used in the action bar and there can be maximum 2 buttons (primary and secondary).
- Title is limited to 2 lines, above that it is displayed as “...”.
- Modals are always centered on the page, with an overlay behind them that hides the page content.
- Weight of the modal depends on the screen size. Modal is positioned with 16px padding from the page edges.
- Height of the modal depends on the content height. For long content that does not fit on the page, the dialog action area remains sticky at the bottom of the modal so that it appears on the page.
- Overlay has Neutral Darker Color (#273142) with %70 of opacity.
- Should respect to [contribution guideline](https://trendyol.github.io/baklava-react-native/?path=/docs/documentation-contribution-guideline--page)

### `Modal` component

Modals inform users about a task and can contain critical information, require decisions, or involve multiple tasks.

#### Properties

| Property        | Description | Default Value |
| --------------- | ----------- | ------------- |
| title (`string`) | title of modal   | -             |
| closeButtonAction (`function`) | close button action of modal  | -             |
| children (`React.Component`) | free area of modal   | -             |
| actionButtonProps (`ButtonProps`) | first buttons' actions  | -             |
| secondActionButtonProps (`ButtonProps`) | second buttons' actions  | -             |

**Comment by buseselvi** [comment]
[Here](https://www.figma.com/file/9r2IU29t66u2rsxX49H8zE/Baklava-Mobile-Design-Guide?type=design&node-id=139%3A2995&mode=design&t=Q1w2Gq8Opa5hmKWe-1) you can reach the Modal Component Design&Documentation. 🚀
