### ISSUE TITLE
Input Component

### ISSUE THREAD

**Issue by dilarakirn** [Trendyol/baklava-react-native#46]
## Design

Figma Design Document

## Implementation

General usage example:

```jsx
<Component>Example</Component>
```

### Rules

Put some rules about how this component should behave and implemented

- Rule 1
- Rule 2

### `Component` component

Description

#### Properties

| Property        | Description | Default Value |
| --------------- | ----------- | ------------- |
| attr (`string`) | attr desc   | -             |

**Comment by pinarkizilarslan** [comment]
hello, this issue has been made before. 
See: https://github.com/Trendyol/baklava-react-native/issues/13
