### ISSUE TITLE
Badge: Background color cannot use the theme colors

### ISSUE THREAD

**Issue by pinarkizilarslan** [Trendyol/baklava-react-native#54]
**Describe the bug**
Badge's background color cannot use the colors in the theme.

**Expected behavior**
Given backgroundColor="featuredBackground" I see the featuredBackground color.

**Screenshots**
![image](https://github.com/Trendyol/baklava-react-native/assets/63308712/db4d0e8e-aa36-4608-829e-d73fdf2729a5)

Expected:
![Screen Shot 2023-08-22 at 10 52 02](https://github.com/Trendyol/baklava-react-native/assets/63308712/e7fd0337-8543-40d2-b9b5-5b96a0538273)

**Comment by zaferatli** [comment]
Hi, i think its use to be like:

backgroundColor:{theme.colors.featuredBackground}

when pass string, in component need to string parser and comprage theme colors when not match will use as color value.

If that bug is confirm as you write, i can fix. Thanks

**Comment by pinarkizilarslan** [comment]
> Hi, i think its use to be like:
> 
> backgroundColor:{theme.colors.featuredBackground}
> 
> when pass string, in component need to string parser and comprage theme colors when not match will use as color value.
> 
> If that bug is confirm as you write, i can fix. Thanks

Hello! First of all, sorry for the late reply.
Due to the bug, the component needs to be refactored. We decided to proceed internally.
Thank you for your attention.

**Comment by ergenekonyigit** [comment]
resolved with https://github.com/Trendyol/baklava-react-native/releases/tag/v2.9.1
