### ISSUE TITLE
Input: The label contains text such as optional which cannot be changed by user.

### ISSUE THREAD

**Issue by mehmetranas** [Trendyol/baklava-react-native#56]
**Describe the bug**
The optional text in the input component should be changeable.

**To Reproduce**

1. Add a input component with required false property.
2. Add a label title
4. See label as "foo-lable (optional)"
**Expected behavior**
As a user, I may not want to see text like 'optional'.

**Screenshots**
![Screenshot 2023-10-09 at 17 26 13](https://github.com/Trendyol/baklava-react-native/assets/22976771/3434e8f3-ec48-4ba8-afb9-77648c9148cd)

**Smartphone:**

- Device: iPhone15
- OS: iOS17
- Version: 2.7.1

**Comment by ergenekonyigit** [comment]
Thanks for the issue. Currently input required/optional behaves opposite to what we expect. We discussed this situation internally, so we will change the behavior to what you expected.

**Comment by aliziyacevik** [comment]
Hello @ergenekonyigit, if this matter is still ongoing, I can offer my assistance.

**Comment by pinarkizilarslan** [comment]
Hello @aliziyacevik, a design change is being made by the designers here. We are waiting there. We thank you for your interest.

**Comment by aliziyacevik** [comment]
You can always reach out to me if a hand is needed! @pinarkizilarslan . Thanks for your response.
