### ISSUE TITLE
TextArea: errorState's border color is not working properly.

### ISSUE THREAD

**Issue by pinarkizilarslan** [Trendyol/baklava-react-native#62]
**Describe the bug**
The border color of textArea's errorState must be dangerColor. In some cases it does not work properly.

**Expected behavior**
The border color must be dangerColor until errorState is false.

**Screenshots**
<img width="334" alt="Screenshot 2024-02-07 at 10 24 33" src="https://github.com/Trendyol/baklava-react-native/assets/63308712/0ed3c90e-0cd8-417b-b82e-c187aeb5019e">

**Comment by yakupozbaydar** [comment]
Thats caused by checking focused state before error state.
Here is a PR for condition and test description 

https://github.com/Trendyol/baklava-react-native/pull/66

**Comment by pinarkizilarslan** [comment]
Thanks for your contribution @yakupozbaydar 🎉

**Comment by yakupozbaydar** [comment]
@pinarkizilarslan  thanks for merge,can you also check my other pr #65
